name: fqr_code
version: 1.0.0
publish_to: none
description: Example QR Code application
environment: 
  sdk: '>=2.19.6 <3.0.0'

dependencies: 
  cupertino_icons: ^1.0.2
  get: 4.6.5
  flutter: 
    sdk: flutter
  firebase_core: ^2.10.0
  firebase_auth: ^4.4.2
  cloud_firestore: ^4.5.2
  qr_flutter: ^4.0.0
  open_file: ^3.2.1
  path_provider: ^2.0.14
  pdf: ^3.6.4
  google_fonts: ^4.0.3
  flutter_barcode_scanner: ^2.0.0
  intl: ^0.17.0

dev_dependencies: 
  flutter_lints: ^2.0.0
  flutter_test: 
    sdk: flutter

flutter:
  assets:
    - assets/OpenSans-Regular.ttf
    - assets/OpenSans-Bold.ttf
    - assets/OpenSans-Italic.ttf
    - assets/OpenSans-BoldItalic.ttf
  uses-material-design: true


